# bash gen_pubspec_dart.sh ./pubspec.yaml ./pubspec.dart

name: foo
description: Hello world! # Example of no formatting and no commentary.
environment:
  sdk: '>=2.17.6 <3.0.0'
# Example of commentary and strange formatting.

platforms:
  web:

# Example commentary.

dev_dependencies:
  dep1: ^1.2.3
  dep2: ^2.3.4
